print('Please enter the following:')
adjective=input('adjective:')
animal=input('animal:')
verb=input('verb:')
exclamation=('exclamation:')
verb1=input('verb:')
verb2=input('verb:')
adjective1=input('adjective:')
print('Your story is:')
print('The other day, I was really in trouble. It all started when I saw a very'+' '+ adjective+' '+' '+ animal+' '+verb+' '+'down the highway.' ' '+exclamation.capitalize()+' '+'I yelled. But all I could think to do was'+' '+ verb2+' '+'right in front of my family. When I woke up , I realized it was just a'+' '+ adjective1+' '+ 'dream.')