
child_meal= float(input('Please enter the price of the meal for child. '))
adult_meal=float(input('Please enter the price of the meal for adult. '))
number_of_children= int(input('How many children are there? '))
number_of_adult=int(input('How many adults are there? '))
tax_rate=float(input('What is the sales tax rate? '))
subtotal=float((adult_meal * number_of_adult)) + float((child_meal * number_of_children))
print(f'Subtotal = $ {subtotal:.2f}')
print(f'Sales Tax = $ {tax_rate:.2f}')
total=float(subtotal) + float(tax_rate)
print(f'Total Sales = $ {total:.2f}')
payment_received= float(input('Please enter amount of payment received. '))
change=float((payment_received)-float (total))
print(f'Change = $ {change:.2f}')